# Generated by Django 4.2.11 on 2024-04-11 04:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_hotels_availability"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotels",
            old_name="name",
            new_name="hotel_name",
        ),
    ]
